### ISSUE TITLE
Update 0.91 - Neo Coolcam smart power Plug, lacks functionality after update

### ISSUE THREAD

**Issue by Beejeedeb** [mozilla-iot/zwave-adapter#86]
Hi,

After updating from 0.9 to 0.9.1 I have the following problem:

Neo Coolcam smart power Plug is only seen as a on/off switch and lacks the other functionality it had in version 0.9. See below pictures.

Version 0.9
![version 0 9](https://user-images.githubusercontent.com/51539492/63956429-ac7fdd00-ca86-11e9-9d37-ceeaba1d6f72.png)

Version 0.9.1
![version 0 9 1](https://user-images.githubusercontent.com/51539492/63956793-7000b100-ca87-11e9-979c-eb4917dcc983.png)

I have reset the Aeotec Z-Stick (Gen5), reinstalled the z-wave add-on and reconnected all the z-wave devices. The Neo Coolcam smart power Plug still lacks before functionality.

I use:
Raspberry PI 
Aeotec Z-Stick (Gen5)
Neo Coolcam smart power Plug

**Comment by dhylands** [comment]
Would you be able to run the command line tool described here: https://github.com/mozilla-iot/wiki/wiki/Command-Line-Tool and send me the output of the `info` command for your device? That will allow me to figure out where things got screwed up and once fixed, I can add the json output to the classifier tests so that it won't happen again.

**Comment by Beejeedeb** [comment]
Information about powerplug is send to your e-mail address.

**Comment by Beejeedeb** [comment]
thanks for fixing it, version 0.9.3 solved the problem, power plug shows again al the power information
